name: Build
on:
  push:
    branches: main
  pull_request:

env:
  NEXT_PUBLIC_ADMIN_URL: http://localhost:3001

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run build
        run: pnpm build
