name: Test
on:
  push:
    branches: main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run test
        run: pnpm test
