name: Test
on:
  push:
    branches: main
  pull_request:

env:
  NEXT_PUBLIC_ADMIN_URL: http://localhost:3001
  NEXT_PUBLIC_WEB_URL: http://localhost:3000
  TZ: UTC

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run test
        run: pnpm test
